# docker-compose.yml
version: '2'
services:
    db:
        image: mariadb:5.5
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
            MYSQL_DATABASE: "dev"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "123456"
    chub:
        build: ./
        ports:
            - "3000:3000"
        depends_on:
            - db
        links:
            - db
